config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/login", to: "sessions#new"
  get "/signup", to: "users#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/search", to: "filters#show"
  resources :orders, only: %i(index destroy create) do
    resources :order_details, only: :index
  end
  resources :users, except: %i(index destroy)
  resources :products, only: :show
  resources :ratings, only: %i(show create update)
  resources :comments, only: %i(create destroy)
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(index show destroy)
  resources :suggests, only: %i(new create)
  resource :cart, except: %i(index new edit)
  resource :languages, only: :show
  %w(404 422 500).each do |code|
    match code, to: "errors#show", code: code, via: %i(get post put patch delete)
  end
  namespace :admin do
    root "static_pages#index"
    resources :categories, except: :show
    resources :users, only: %i(index destroy)
    resources :products, except: :show do
      collection do
        get :import, to: "import_products#new"
        post :import, to: "import_products#create"
      end
    end
    resources :orders, only: %i(index update) do
      resources :order_details, only: :index
    end
    resources :suggests, only: %i(index destroy update)
    get "statistics", to:"statistics#index"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: {pending: 0, accept: 1, reject: 2}
  belongs_to :user
  has_many :order_details, dependent: :destroy
  delegate :email, to: :user, prefix: :user, allow_nil: true
  delegate :name, to: :user, prefix: :user, allow_nil: true
  scope :created_at_desc, ->{order created_at: :desc}
  scope :rank, ->(start){select("@row:=@row+1 as rank, orders.*").from("orders, (SELECT @row:=#{start}) as r")}
  scope :total_on, ->(date){where("date(created_at) = ?", date).sum("total")}
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < AdminBaseController
    before_action :find_order, only: :update

    def index
      page = valid_page params[:page]
      per_page = Settings.admin.orders.number_of_orders
      @orders = Order.created_at_desc.rank((page - 1) * per_page).paginate page: page,
        per_page: per_page
      respond_to do |format|
        format.html
        format.js
      end
    end

    def update
      status = params[:status].to_i
      if (check_status status) && (@order.update_attribute :status, status)
        Admin::OrderMailer.admin_respon(@order.user, @order).deliver_now
        @order.order_details.each(&:return_quantity_when_reject) if @order.reject?
        flash[:success] = t ".update_success"
      else
        flash[:danger] = t ".update_failed"
      end
      redirect_to admin_orders_path
    end

    private

    def find_order
      @order = Order.find_by id: params[:id]
      return if @order
      flash[:danger] = t "admin.orders.not_found_order"
      redirect_to admin_orders_path
    end

    def check_status status
      array = Order.statuses.values
      true if array.include? status
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :logged_in_user, only: %i(index destroy create)
  before_action :current_order, only: %i(create)
  before_action :find_order, only: %i(destroy)

  def index
    @orders = @current_user.orders.created_at_desc.paginate page: valid_page(params[:page]),
      per_page: Settings.orders.number_of_orders
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @order = @current_user.orders.new
    session[:shopping_cart].each do |item|
      @order.order_details << @order.order_details.new(item)
    end
    if @order.save
      flash[:success] = t ".order_success"
      OrderMailer.user_order(@order).deliver_now
      session[:shopping_cart] = []
    else
      flash[:danger] = t ".order_failed"
    end
    redirect_to cart_path
  end

  def destroy
    if @order.pending? && @order.destroy
      flash[:success] = t ".delete_success"
    else
      flash[:danger] = t ".delete_failed"
    end
    redirect_to orders_path
  end

  private

  def find_order
    @order = @current_user.orders.find_by id: params[:id]
    return if @order
    flash[:danger] = t "orders.not_found_order"
    redirect_to orders_path
  end
end

app/views/admin/orders/_list_order.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t ".list_order" %>
  </div>
  <div class="panel-body">
    <div class="wishlist-item table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th><%= t "admin.orders.index.rank" %></th>
            <th><%= t "admin.orders.index.user_email" %></th>
            <th><%= t "admin.orders.index.user_name" %></th>
            <th><%= t "admin.orders.index.total" %></th>
            <th><%= t "admin.orders.index.status" %></th>
            <th><%= t "admin.orders.index.created_at" %></th>
            <th><%= t "admin.orders.index.updated_at" %></th>
            <th><%= t "admin.orders.index.function" %></th>
          </tr>
        </thead>
        <tbody id="list-order">
          <%= render partial: "order", collection: @orders %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= will_paginate @orders %>

app/views/admin/orders/_order.html.erb
<tr>
  <td><%= order.rank.to_i %></td>
  <td><%= order.user_email %></td>
  <td><%= order.user_name %></td>
  <td><%= order.total %></td>
  <td>
    <span class="label label-<%= order.status %>">
      <%= order.status %>
    </span>
  </td>
  <td><%= l order.created_at %></td>
  <td><%= l order.updated_at %></td>
  <td>
    <%= link_to admin_order_order_details_path(order_id: order.id), title: t(".detail") do %>
      <i class="fa fa-info"></i>
    <% end %>
    <% if order.pending? %>
      |
      <%= link_to admin_order_path(id: order.id, status: 1),
        method: :patch, title: t(".accept") do %>
        <i class="fa fa-check"></i>
      <% end %>
      |
      <%= link_to admin_order_path(id: order.id, status: 2),
        method: :patch, title: t(".reject") do %>
        <i class="fa fa-ban"></i>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/admin/orders/index.html.erb
<% provide :title, t(".manage_orders_title") %>
<div id="page-wrapper" class="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header"><%= t "admin.layouts.manage_orders" %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12" id="list-order">
    <%= render "list_order" %>
    </div>
  </div>
</div>

app/views/admin/orders/index.js.erb
$('#list-order').html('<%= j(render('admin/orders/list_order')) %>');
$('.pagination a').attr('data-remote', 'true');