config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/login", to: "sessions#new"
  get "/signup", to: "users#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/search", to: "filters#show"
  resources :orders, only: %i(index destroy create) do
    resources :order_details, only: :index
  end
  resources :users, except: %i(index destroy)
  resources :products, only: :show
  resources :ratings, only: %i(show create update)
  resources :comments, only: %i(create destroy)
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(index show destroy)
  resources :suggests, only: %i(new create)
  resource :cart, except: %i(index new edit)
  resource :languages, only: :show
  %w(404 422 500).each do |code|
    match code, to: "errors#show", code: code, via: %i(get post put patch delete)
  end
  namespace :admin do
    root "static_pages#index"
    resources :categories, except: :show
    resources :users, only: %i(index destroy)
    resources :products, except: :show do
      collection do
        get :import, to: "import_products#new"
        post :import, to: "import_products#create"
      end
    end
    resources :orders, only: %i(index update) do
      resources :order_details, only: :index
    end
    resources :suggests, only: %i(index destroy update)
    get "statistics", to:"statistics#index"
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :load_product, only: %i(create destroy update)
  before_action :current_order, only: %i(show)

  def show
    @order_details = []
    session[:shopping_cart].each do |e|
      @order_details << OrderDetail.new(e)
    end
  end

  def create
    order_detail = OrderDetail.new item_params
    result = find_product_in_cart(order_detail.product_id)
    if order_detail.quantity.nil? || order_detail.quantity <= 0
      flash[:danger] = t ".failed_add"
    elsif result
      check_quantity result, order_detail.quantity
    else
      session[:shopping_cart] << order_detail
      flash[:success] = t ".success_add"
    end
    redirect_to cart_path
  end

  def update
    quantity = params[:quantity].to_i
    if quantity > @product.quantity || quantity <= 0
      flash[:danger] = t ".invalid_quantity"
    else
      result = find_product_in_cart(@product.id)
      result["quantity"] = quantity
    end
    redirect_to cart_path
  end

  def destroy
    session[:shopping_cart].each do |item|
      session[:shopping_cart].delete(item) if item["product_id"] == @product.id
    end
    flash[:success] = t ".success_delete"
    redirect_to cart_path
  end

  private

  def item_params
    params.permit :product_id, :quantity
  end

  def load_product
    current_order
    @product = Product.find_by id: params[:product_id]
    return if @product
    flash[:danger] = t "products.not_found_product"
    redirect_to root_path
  end

  def find_product_in_cart product_id
    result = nil
    session[:shopping_cart].each do |item|
      next unless item["product_id"] == product_id
      result = item
    end
    result
  end

  def check_quantity result, quantity
    if result["quantity"] + quantity > @product.quantity
      flash[:danger] = t ".invalid_quantity"
    else
      result["quantity"] += quantity
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def total_price order_details
    total = 0
    order_details.each do |item|
      total += calc_price item.product_price, item.quantity
    end
    total
  end
end

app/views/carts/_order_cart.html.erb
<tr>
  <td class="cart_product">
    <%= link_to order_detail.product do %>
      <%= image_tag order_detail.product_picture.url %>
    <% end %>
  </td>
  <td class="cart_description">
    <p class="product-name">
      <%= link_to order_detail.product do %>
        <%= order_detail.product_name %>
      <% end %>
    </p>
  </td>
  <td class="price"><span><%= order_detail.product_price %></span></td>
  <td class="qty">
    <%= form_tag cart_path(product_id: order_detail.product_id), method: :patch do %>
      <%= number_field_tag :quantity, nil, class: "form-control input-sm",
        min: Settings.products.min_quantity, max: order_detail.product_quantity,
        value: order_detail.quantity %> <br />
      <%= button_tag type: "submit", class: "btn", name: nil do %>
        <%= content_tag :span, t(".apply") %>
      <% end %>
    <% end %>
  </td>
  <td class="price">
    <span>
      <%= calc_price order_detail.product_price, order_detail.quantity %>
    </span>
  </td>
  <td class="action">
    <%= link_to cart_path(product_id: order_detail.product_id), method: :delete,
      data: {confirm: t("carts.confirm")} do %>
      <%= content_tag :i, "", class: "icon-close" %>
    <% end %>
  </td>
</tr>

app/views/carts/_shopping_cart.html.erb
<div class="order-detail-content">
  <div class="table-responsive">
    <table class="table table-bordered cart_summary">
      <thead>
        <tr>
          <th class="cart_product"><%= t ".product" %></th>
          <th><%= t ".name" %></th>
          <th><%= t ".price" %></th>
          <th><%= t ".quantity" %></th>
          <th><%= t ".total_label" %></th>
          <th class="action"><i class="fa fa-trash-o"></i></th>
        </tr>
      </thead>
      <tbody>
        <% if @order_details.any? %>
          <%= render partial: "order_cart", collection: @order_details, as: :order_detail %>
        <% else %>
          <tr><td colspan="6"><%= t ".no_item" %></td></tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="2" rowspan="2"></td>
          <td colspan="3"><strong><%= t ".total_label" %></strong></td>
          <td colspan="2">
            <strong id="cart-total-price">
              <%= t ".total", price: total_price(@order_details) %>
            </strong>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
  <div class="cart_navigation">
    <% if @order_details.any? %>
      <%= link_to orders_path, class: "checkout-btn", method: :post do %>
        <i class="fa fa-check"></i><%= t ".checkout" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/carts/show.html.erb
<% provide :title, t("carts.shopping_title") %>
<section class="main-container col1-layout">
  <div class="main container">
    <div class="col-main">
      <div class="cart">
        <div class="page-content page-order">
          <div class="page-title">
            <h2><%= t "carts.shopping_title" %></h2>
          </div>
          <%= render "shopping_cart" %>
        </div>
      </div>
    </div>
  </div>
</section>