config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/login", to: "sessions#new"
  get "/signup", to: "users#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/search", to: "filters#show"
  resources :orders, only: %i(index destroy create) do
    resources :order_details, only: :index
  end
  resources :users, except: %i(index destroy)
  resources :products, only: :show
  resources :ratings, only: %i(show create update)
  resources :comments, only: %i(create destroy)
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(index show destroy)
  resources :suggests, only: %i(new create)
  resource :cart, except: %i(index new edit)
  resource :languages, only: :show
  %w(404 422 500).each do |code|
    match code, to: "errors#show", code: code, via: %i(get post put patch delete)
  end
  namespace :admin do
    root "static_pages#index"
    resources :categories, except: :show
    resources :users, only: %i(index destroy)
    resources :products, except: :show do
      collection do
        get :import, to: "import_products#new"
        post :import, to: "import_products#create"
      end
    end
    resources :orders, only: %i(index update) do
      resources :order_details, only: :index
    end
    resources :suggests, only: %i(index destroy update)
    get "statistics", to:"statistics#index"
  end
end

app/models/suggest.rb
class Suggest < ApplicationRecord
  enum status: {pending: 0, accept: 1, reject: 2}
  belongs_to :user
  belongs_to :category
  delegate :name, to: :category, prefix: :category, allow_nil: true
  delegate :email, to: :user, prefix: :user, allow_nil: true
  validates :product_name, presence: true, length: {maximum: Settings.suggests.max_length_name}
  validates :detail, presence: true, length: {maximum: Settings.suggests.max_length_detail}
end

app/controllers/admin/suggests_controller.rb
module Admin
  class SuggestsController < AdminBaseController
    before_action :find_suggest, only: %i(destroy update)

    def index
      @suggests = Suggest.all.paginate page: params[:page],
        per_page: Settings.admin.suggests.number_of_suggests
      respond_to do |format|
        format.html
        format.js
      end
    end

    def destroy
      if @suggest.destroy
        flash[:success] = t ".delete_success"
      else
        flash[:danger] = t ".delete_failed"
      end
      redirect_to admin_suggests_path
    end

    def update
      status = params[:status].to_i
      if (check_status status) && @suggest.update_attribute(:status, status)
        flash[:success] = t ".success"
      else
        flash[:danger] = t ".failed"
      end
      redirect_to admin_suggests_path
    end

    private

    def check_status status
      array = [Settings.suggests.accept_status, Settings.suggests.reject_status]
      true if array.include? status
    end

    def find_suggest
      @suggest = Suggest.find_by id: params[:id]
      return if @suggest
      flash[:danger] = t "error_sign_up"
      redirect_to admin_suggests_path
    end
  end
end

app/controllers/suggests_controller.rb
class SuggestsController < ApplicationController
  before_action :logged_in_user, only: %i(new)

  def new
    @suggest = Suggest.new
  end

  def create
    @suggest = current_user.suggests.build suggest_params
    if @suggest.save
      flash[:success] = t ".suggest_success"
      redirect_to root_url
    else
      flash[:danger] = t ".suggest_fail"
      render :new
    end
  end

  private

  def suggest_params
    params.require(:suggest).permit :product_name, :category_id, :detail
  end
end

app/views/admin/suggests/_list_suggest.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t ".list_suggest" %>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th><%= t "admin.suggests.index.id" %></th>
            <th><%= t "admin.suggests.index.email" %></th>
            <th><%= t "admin.suggests.index.product_name" %></th>
            <th><%= t "admin.suggests.index.category" %></th>
            <th><%= t "admin.suggests.index.detail" %></th>
            <th><%= t "admin.suggests.index.status" %></th>
            <th><%= t "admin.suggests.index.function" %></th>
          </tr>
        </thead>
        <tbody id="list-suggest">
          <%= render partial: "suggest", collection: @suggests %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= will_paginate @suggests %>

app/views/admin/suggests/_suggest.html.erb
<tr>
  <td><%= suggest.id %></td>
  <td><%= suggest.user_email %></td>
  <td><%= suggest.product_name %></td>
  <td><%= suggest.category_name %></td>
  <td><%= suggest.detail %></td>
  <td>
    <span class="label label-<%= suggest.status %>">
      <%= suggest.status %>
    </span>
  </td>
  <td>
    <%= link_to admin_suggest_path(suggest), method: :delete,
      data: {confirm: t("admin.suggests.destroy.confirm")} do %>
      <i class="fa fa-trash-o"></i>
    <% end %>
    <% if suggest.pending? %>
      |
      <%= link_to admin_suggest_path(id: suggest.id, status: Settings.suggests.accept_status),
        method: :patch do %>
        <i class="fa fa-check"></i>
      <% end %>
      |
      <%= link_to admin_suggest_path(id: suggest.id, status: Settings.suggests.reject_status),
        method: :patch do %>
        <i class="fa fa-times"></i>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/admin/suggests/index.html.erb
<% provide :title, t(".manage_suggests_title") %>
<div id="page-wrapper" class="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header"><%= t "admin.layouts.manage_suggests" %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12" id="list-suggest">
    <%= render "list_suggest" %>
    </div>
  </div>
</div>

app/views/admin/suggests/index.js.erb
$('#list-suggest').html('<%= j(render('admin/suggests/list_suggest')) %>');
$('.pagination a').attr('data-remote', 'true');